version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: nlrunner
      MYSQL_DATABASE: nlrunner_db
      MYSQL_USER: nlrunner
      MYSQL_PASSWORD: nlrunner
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-boot-app:
    build:
      context: ./throw_wa_backend/throw_wa
      dockerfile: Dockerfile
    container_name: spring-boot-app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: nlrunner
      MYSQL_PASSWORD: nlrunner
      MYSQL_DATABASE: nlrunner_db
    ports:
      - "8000:8000"

  fastapi-app:
    build:
      context: ./throw_wa-4/backend
      dockerfile: Dockerfile
    container_name: fastapi-app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: nlrunner
      MYSQL_PASSWORD: nlrunner
      MYSQL_DATABASE: nlrunner_db
    ports:
      - "8080:8080"
